Gradebook.Web/Controllers/NavigationController.cs
using System.Web.Mvc;
using Gradebook.Business.Enums;
using Gradebook.Web.Common.GradebookPrincipalService;

namespace Gradebook.Web.Controllers
{
    [ChildActionOnly]
    public class NavigationController : Controller
    {
        public ActionResult LeftMenu()
        {
            var userType = User.Identity.IsAuthenticated ? ((GradebookPrincipal)User).UserType : UserType.None;
            return PartialView(userType);
        }

        public ActionResult TopRightMenu()
        {
            return PartialView(User.Identity.IsAuthenticated);
        }
    }
}

Gradebook.Web/Views/Shared/ErrorDialog.cshtml
<div id="error-dialog" style="display: none;" title="Download complete">
    <p id="error-dialog-message">
    </p>
</div>

Gradebook.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUi")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/jqueryUiCss")
    @Scripts.Render("~/bundles/jqueryval")

</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(i18n.Gradebook, "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                @Html.Action("TopRightMenu", "Navigation")
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                @Html.Action("LeftMenu", "Navigation")
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                @RenderBody()
                <hr/>
                <footer>
                    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </footer>
            </div>
        </div>
    </div>

    @Html.Partial("ErrorDialog")
</body>
</html>

Gradebook.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryUi")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/bundles/jqueryUiCss")
    @Scripts.Render("~/bundles/jqueryval")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(i18n.Gradebook, "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                @Html.Action("TopRightMenu", "Navigation")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Html.Partial("ErrorDialog")
</body>
</html>